### PR TITLE
🔴🔵⚪️🟡🟢🟣📏6 FT RADIUS📏🟣🟢🟡⚪️🔵🔴

### LINKED ISSUE #11: social distance scale up request
The diagram included in the README suggests that social distancing only requires a 3ft radius surrounding an individual. 

The Centers for Disease Control and Prevention ([CDC](https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/social-distancing.html)) have provided guidance to `Stay at least 6 feet (2 meters) from other people`. 

Here is the diagram in question:
image

### PR DESCRIPTION
**Pull request by jusleg**
closes: #11 
https://web.njit.edu/~cm395/theBeeMovieScript/

### CODE REVIEW

**Comment by jusleg** [comment]
@hughxie

**Comment by xie** [comment]
Amazing work!

**Review by almiche — COMMENTED** [review]
Much needed 🙏

**Comment by almiche** [comment]
High impact at its finest

**Pull request merged**
